services:
  postgres:
    image: postgres
    ports:
      - 5433:5432
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: emir0416
      POSTGRES_DB: jobber-auth

    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  pulsar:
    image: apachepulsar/pulsar:latest
    command: >
      /pulsar/bin/pulsar standalone
    ports:
      - 6650:6650

volumes:
  postgres_data: